### ISSUE TITLE
Bot sometimes stops after going through gate.

### ISSUE THREAD

**Issue by SurgicalSheep** [Dementor42/darkorbit-pixel-bot#8]
After ship dies, when bot goes through a gate, it just stops
![Screenshot_5](https://user-images.githubusercontent.com/43825220/86179325-f19af280-bb21-11ea-8bdb-6e75e8d7e36d.png)

**Comment by Dementor42** [comment]
Hi @SurgicalSheep thanks for reporting. After a long time, I just fixed the problem. (see commit f46fc0eeff6acf859d57451f1f23ff98858df8fe)
